name: Snyk Scan

on:
  pull_request_target:
    branches: [ main ]
  schedule:
    - cron: '15 0 * * 2'

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Clean
        run: dotnet clean && dotnet nuget locals all --clear
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=dotnetnotts.sln
